apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: stress-deployment 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: stress 
  template: 
    metadata: 
      labels: 
        app: stress 
    spec: 
      containers: 
      - name: stress 
        image: alpine 
        command: ["/bin/sh", "-c", "apk add --no-cache stress-ng && stress-ng --cpu 2 --timeout 60s"] 
        resources: 
          requests: 
            memory: "64Mi" 
            cpu: "250m" 
          limits: 
            memory: "128Mi" 
            cpu: "500m"
